### ISSUE TITLE
Stop preventing consolidate record when bbox is invalid

### ISSUE THREAD

**Issue by tusbar** [geodatagouv/geoplatform#2]
```js
Error: bbox must only contain numbers
    at /Users/tusbar/dev/geodatagouv/geoplatform/node_modules/@turf/turf/turf.js:698:35
    at Array.forEach (<anonymous>)
    at validateBBox (/Users/tusbar/dev/geodatagouv/geoplatform/node_modules/@turf/turf/turf.js:697:10)
    at bboxPolygon (/Users/tusbar/dev/geodatagouv/geoplatform/node_modules/@turf/turf/turf.js:7064:5)
    at metadata.identificationInfo.extent.map.filter.map.bbox (/Users/tusbar/dev/geodatagouv/geoplatform/lib/metadata/iso/extent.js:48:18)
    at Array.map (<anonymous>)
    at exports.getConsolidatedExtent (/Users/tusbar/dev/geodatagouv/geoplatform/lib/metadata/iso/extent.js:48:6)
    at convert (/Users/tusbar/dev/geodatagouv/geoplatform/lib/metadata/iso/index.js:64:28)
    at createDatasetFromRecord (/Users/tusbar/dev/geodatagouv/geoplatform/lib/jobs/consolidate-record/index.js:98:12)
    at Object.consolidateRecord [as handler] (/Users/tusbar/dev/geodatagouv/geoplatform/lib/jobs/consolidate-record/index.js:32:22)
    at <anonymous>
```

**Comment by tusbar** [comment]
Examples:

- 1edc94510a82f1e369e27234e1dc674cb85c0f8e
- b004cb02c5d1cd0dd67eec490e09cf3312cd72c9

**Comment by tusbar** [comment]
https://sentry.data.gouv.fr/etalab/geoplatform-workers/issues/635436/
